thresholds: &thresholds-vatten
  - {color: "green", level: 100}
  - {color: "orange", level: 400}
  - {color: "red", level: 700}

cells:
  pool:
    dataRef: tank_hojd_mm
    label:
      text: "${value} mm"
    fillColor:
      thresholds: *thresholds-vatten
    fillLevel:
      thresholdLwrFillPercent: 0
      thresholdUprFillPercent: 100
      thresholdLwrValue: 0
      thresholdUprValue: 1000
      fillDirection: 'bottomToTop'

mappings:
  - query: A
    field: tank_hojd_mm
    unit: lengthmm
    label: "Vattennivå"
    text: "${value} mm"
    icon: fa-tint
    thresholds: *thresholds-vatten
